
android-sdk:
  build: android-sdk


data_storage:
  build: data
  volumes:
  - /usr/local/apache2/htdocs/
  - /opt/android-sdk-linux
  volumes_from:
  - android-sdk
   
httpd:
  build: httpd
  ports:
   - "80:80"
  volumes_from:
   - data_storage


jenkins:
  build: jenkins
  ports:
   - "5000:5000"
   - "8080:8080"
  volumes:
  - /opt/android-sdk-linux
  volumes_from:
   - data_storage


nexus:
  image: sonatype/nexus:oss
  ports:
   - "8081:8081"
  volumes_from:
   - data_storage

