
data_storage:
  build: ../data

jenkins:
  build: ../jenkins
  ports:
   - "5000:5000"
   - "8080:8080"
  volumes_from:
   - data_storage


nexus:
  image: sonatype/nexus:oss
  ports:
   - "8081:8081"
  volumes_from:
   - data_storage

