
data_storage:
  image: ubuntu:14.04
  container_name: data
  volumes:
  - /data/docker/apache2:/usr/local/apache2/htdocs:rw
  - /data/docker/jenkins:/var/jenkins_home:rw
  - /data/docker/nexus:/sonatype-work:rw
  - /data/docker/psql:/var/lib/postgresql/data:rw

httpd:
  build: httpd
  container_name: http-front
  ports:
  - "80:80"
  volumes_from:
  - data_storage

jenkins:
  image: jenkins
  container_name: jenkins-app
  ports:
  - "5000:5000"
  - "8080:8080"
  volumes_from:
  - data_storage

nexus:
  image: sonatype/nexus:oss
  container_name: nexus-app
  ports:
  - "8081:8081"
  volumes_from:
  - data_storage

sonarqube-db:
  image: postgres
  container_name: sonarqube-db
  ports:
  - "5432:5432"
  volumes_from:
  - data_storage
  environment:
  - POSTGRES_USER=sonar
  - POSTGRES_PASSWORD=sonar

sonarqube:
  image: sonarqube
  container_name: sonarqube-app
  ports:
  - "9000:9000"
  - "9092:9092"
  volumes_from:
  - data_storage
  environment:
  - SONARQUBE_JDBC_USERNAME=sonar
  - SONARQUBE_JDBC_PASSWORD=sonar
  - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar






